"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z5&#d*iyfhhyu1rqtlbfu^67o*^*m8#8*jnpc-0_m(o3os%-p9'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://dd3f-2401-4900-8fd1-a86a-d089-edf9-2a7e-3a36.ngrok-free.app",
    "https://dd74-2401-4900-8fd1-a86a-d089-edf9-2a7e-3a36.ngrok-free.app",
    "https://6dec-2401-4900-8fd1-a86a-d089-edf9-2a7e-3a36.ngrok-free.app",
    "https://77d3-2401-4900-8fd1-a86a-4db2-d1cc-6ce5-ad2.ngrok-free.app",
    "https://f0fe-117-194-4-8.ngrok-free.app",
    "http://127.0.0.1:8000/upstox-callback/"
]

CSRF_COOKIE_SECURE = False

# Angel Broking API Credentials
ANGEL_API_KEY = "GBCZDrbe"
ANGEL_API_SECRET = "a19b3b69-1575-4e26-aeda-4361b269f317"
ANGEL_REDIRECT_URI = "https://f0fe-117-194-4-8.ngrok-free.app/angel-one-callback/"

# Angel One API Login URL
ANGEL_ONE_LOGIN_URL = "https://smartapi.angelone.in/publisher-login?api_key={}&state={}&redirect_uri={}".format(
    ANGEL_API_KEY, 
    "statevariable", 
    ANGEL_REDIRECT_URI
)

# Upstox API Credentials
UPSTOX_API_KEY = "8f1ab0d3-bdba-469e-a2fc-a29237e4c032"
UPSTOX_API_SECRET = "34jbwppkm3"
UPSTOX_REDIRECT_URI = "http://127.0.0.1:8000/upstox-callback/"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Store in DB
SESSION_COOKIE_AGE = 86400  # 1-day session
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = False  # Only if using HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_NAME = "sessionid"

# Add your OpenAI API key
# OPENAI_API_KEY = ''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'store': {  # Replace with your app name
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}